version: 2

models:
  - name: stg_website_events
    description: Cleaned and transformed in-app events with proper timestamp formatting
    columns:
      - name: event_id
        description: Unique identifier for the event

        tests:
          - unique
          - not_null
      - name: customer_id
        description: Customer who triggered the event
      - name: event_time
        description: Timestamp when the event occurred (converted from Unix)
      - name: event_name
        description: Name of the event
      - name: platform
        description: Platform where the event occurred

  - name: stg_marketing_campaigns
    description: Aggregated marketing campaign data with duration and spend metrics
    columns:
      - name: campaign_id
        description: Unique campaign identifier
        tests:
          - unique
          - not_null
      - name: campaign_name
        description: Name of the marketing campaign
      - name: campaign_type
        description: Type of campaign
      - name: start_time
        description: Campaign start time
      - name: end_time
        description: Campaign end time
      - name: campaign_duration
        description: Number of events in the campaign
      - name: total_campaign_spent
        description: Total amount spent on the campaign

  - name: stg_flower_orders
    description: >
      This table contains cleaned and processed flower order data
      with proper timestamp formatting
    columns:
      - name: order_id
        description: Unique identifier for the flower order
      - name: customer_id
        description: Customer who placed the order
      - name: order_time
        description: When the order was placed
      - name: order_value
        description: Total value of the order
      - name: flowers_amount
        description: Amount spent on flowers
      - name: vase_amount
        description: Amount spent on vase
      - name: chocolate_amount
        description: Amount spent on chocolate
      - name: delivery_id
        description: Associated delivery identifier
      - name: platform
        description: Platform where the order was placed

  - name: stg_customers
    description: Customer information enriched with marketing and address data
    columns:
      - name: customer_id
        description: Unique customer identifier
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer's first name
      - name: last_name
        description: Customer's last name
      - name: full_name
        description: Customer's full name (concatenated)
      - name: email
        description: Customer's email address
      - name: gender
        description: Customer's gender
      - name: campaign_id
        description: Associated marketing campaign
      - name: campaign_name
        description: Marketing campaign name
      - name: campaign_type
        description: Marketing campaign type
      - name: address_id
        description: Associated address identifier
      - name: full_address
        description: Complete address
      - name: state
        description: State abbreviation

  - name: stg_web_events_per_campaign
    description: Website events enriched with campaign information and aggregated metrics
    columns:
      - name: campaign_id
        description: Campaign identifier (-1 for organic)
      - name: campaign_name
        description: Campaign name (organic for non-campaign events)
      - name: campaign_type
        description: Campaign type (organic for non-campaign events)
      - name: platform
        description: Platform where the event occurred
      - name: event_time
        description: When the event occurred
      - name: total_num_events
        description: Total number of events for this campaign/platform/time combination

